Interface:
    TextInput:
        id: textinput
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.7}
    Label:
        id: label
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.6}
    Button:
        text:"Click Me"
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.5}
        on_press: root.highlight_current_line()
